version: "3.6"

services:
  mysql:
    build: "./mysql"
    restart: "always"
    environment:
      MYSQL_DATABASE: "constanta"
      MYSQL_ROOT_PASSWORD: "pe0038900"
      MYSQL_USER: "badchaos"
      MYSQL_PASSWORD: "pe0038900"
  cpayment:
    build: "."
    command: "go run main.go"
    depends_on:
      - "mysql"
    ports:
      - "9090"
    environment:
       MYSQL_DATABASE: "constanta"
       MYSQL_ROOT_PASSWORD: "pe0038900"
       MYSQL_USER: "badchaos"
       MYSQL_PASSWORD: "pe0038900"
